sudo: false
language: scala
scala:
  - 2.12.5
jdk:
  - openjdk8
script:
  - sbt -Dakka.loglevel=ERROR clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt scalastyle
after_success: sbt codacyCoverage
